export const MIKROTIK_WORKER_TICK_MS = Number(
  process.env.MIKROTIK_WORKER_TICK_MS ?? 30_000,
);

export const MIKROTIK_STATUS_POLL_INTERVAL_MS =
  Number(process.env.MIKROTIK_STATUS_POLL_INTERVAL_SECONDS ?? 30) * 1000;

export const MIKROTIK_METRICS_INTERVAL_MS =
  Number(process.env.MIKROTIK_METRICS_INTERVAL_SECONDS ?? 600) * 1000;

export const DASHBOARD_REFRESH_INTERVAL_MS =
  Number(process.env.DASHBOARD_REFRESH_INTERVAL_SECONDS ?? 30) * 1000;

export const MIKROTIK_WORKER_CONCURRENCY = Number(
  process.env.MIKROTIK_WORKER_CONCURRENCY ?? 8,
);
